apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crypto-app
  template:
    metadata:
      labels:
        app: crypto-app
    spec:
      containers:
        - name: crypto-container
          image: your-docker-image-url
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              cpu: "500m"
              memory: "512Mi"
