apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-price-service
  labels:
    app: crypto-price-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crypto-price-service
  template:
    metadata:
      labels:
        app: crypto-price-service
    spec:
      containers:
        - name: crypto-price-service
          image: 136688660029.dkr.ecr.us-east-1.amazonaws.com/crypto-price-service 
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /bitcoin
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /bitcoin
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 15
