apiVersion: v1
kind: Service
metadata:
  name: crypto-price-service
  labels:
    app: crypto-price-service
spec:
  selector:
    app: crypto-price-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer  # Use ClusterIP if only accessible within the cluster
