name: 'Terraform Deploy'

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform-deploy.yml'
 

permissions:
  id-token: write
  contents: read

jobs:
  pre_run_create_s3_bucket:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Pre-Setup AWS Credentials and create S3 bucket
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          aws configure set aws_access_key_id ${AWS_ACCESS_KEY_ID}
          aws configure set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY}
          aws configure set default.region ${AWS_DEFAULT_REGION}
          
          BUCKET_NAME="cryptos3bucket1"
          if ! aws s3api head-bucket --bucket $BUCKET_NAME 2>/dev/null; then
            aws s3api create-bucket --bucket $BUCKET_NAME
            echo "S3 bucket $BUCKET_NAME created."
          else
            echo "S3 bucket $BUCKET_NAME already exists."
          fi
          

  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: '1.7.0'

    - name: Configure AWS Credentials
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      run: |
        aws configure set aws_access_key_id ${AWS_ACCESS_KEY_ID}
        aws configure set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY}
        aws configure set default.region ${AWS_DEFAULT_REGION}

    - name: Terraform Init
      run: |
        cd terraform
        terraform init \
          -backend-config="bucket=cryptos3bucket" \
          -backend-config="key=terraform.tfstate"

    - name: Terraform Plan
      run: |
        cd terraform
        terraform plan \
          -var="bucket_name=cryptos3bucket1"

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        cd terraform
        terraform apply -auto-approve \
          -var="bucket_name=cryptos3bucket1"

    - name: Terraform Output
      run: |
        cd terraform
        terraform output